# Generated by Django 5.2.7 on 2025-11-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order', 'name'], 'verbose_name': 'หน่วยงาน', 'verbose_name_plural': 'หน่วยงาน'},
        ),
        migrations.AddField(
            model_name='department',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ลำดับการแสดงผล'),
        ),
    ]
