# Generated by Django 5.2.7 on 2025-11-01 06:37

import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('badges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'นาย'), ('mrs', 'นาง'), ('miss', 'นางสาว'), ('prof', 'ศาสตราจารย์'), ('assoc_prof', 'รองศาสตราจารย์'), ('asst_prof', 'ผู้ช่วยศาสตราจารย์'), ('dr', 'ดร.')], max_length=20, verbose_name='คำนำหน้า')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('position', models.CharField(max_length=255, verbose_name='ตำแหน่ง')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมล')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('badge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_profiles', to='badges.badgetype', verbose_name='ประเภทบัตร')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles_created', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_profiles', to='accounts.department', verbose_name='หน่วยงาน')),
            ],
            options={
                'verbose_name': 'ข้อมูลบุคลากร',
                'verbose_name_plural': 'ข้อมูลบุคลากร',
                'db_table': 'staff_profiles',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_photo', models.ImageField(upload_to='photos/original/', verbose_name='รูปภาพต้นฉบับ')),
                ('cropped_photo', imagekit.models.fields.ProcessedImageField(upload_to='photos/cropped/', verbose_name='รูปภาพที่ Crop แล้ว')),
                ('crop_data', models.JSONField(blank=True, help_text='เก็บข้อมูลจาก Cropper.js (x, y, width, height, rotate)', null=True, verbose_name='ข้อมูล Crop')),
                ('file_size', models.IntegerField(default=0, verbose_name='ขนาดไฟล์ (bytes)')),
                ('width', models.IntegerField(default=0, verbose_name='ความกว้าง (px)')),
                ('height', models.IntegerField(default=0, verbose_name='ความสูง (px)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='อัปโหลดเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อัปโหลด')),
                ('staff_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='registry.staffprofile', verbose_name='ข้อมูลบุคลากร')),
            ],
            options={
                'verbose_name': 'รูปภาพ',
                'verbose_name_plural': 'รูปภาพ',
                'db_table': 'photos',
            },
        ),
        migrations.CreateModel(
            name='BadgeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('photo_uploaded', 'อัปโหลดรูปแล้ว'), ('ready_to_submit', 'พร้อมส่ง'), ('submitted', 'ส่งแล้ว'), ('under_review', 'กำลังตรวจสอบ'), ('approved', 'อนุมัติ'), ('rejected', 'ส่งกลับ'), ('badge_created', 'สร้างบัตรแล้ว'), ('printed', 'พิมพ์แล้ว'), ('completed', 'เสร็จสิ้น')], default='draft', max_length=20, verbose_name='สถานะ')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='ส่งเมื่อ')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='ตรวจสอบเมื่อ')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='อนุมัติเมื่อ')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='เหตุผลที่ส่งกลับ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_requests_approved', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ตรวจสอบ')),
                ('staff_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge_request', to='registry.staffprofile', verbose_name='ข้อมูลบุคลากร')),
            ],
            options={
                'verbose_name': 'คำขอออกบัตร',
                'verbose_name_plural': 'คำขอออกบัตร',
                'db_table': 'badge_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
