# Generated by Django 5.2.7 on 2025-11-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='อายุ'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='national_id',
            field=models.CharField(blank=True, help_text='เลขบัตรประชาชน 13 หลัก', max_length=13, null=True, verbose_name='บัตรประชาชน ๑๓ หลัก'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='test_atk',
            field=models.BooleanField(default=False, verbose_name='ATK'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='test_rt_pcr',
            field=models.BooleanField(default=False, verbose_name='RT-PCR'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='test_temperature',
            field=models.BooleanField(default=False, verbose_name='วัดอุณหภูมิ'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='vaccine_dose_1',
            field=models.BooleanField(default=False, verbose_name='วัคซีนเข็ม ๑'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='vaccine_dose_2',
            field=models.BooleanField(default=False, verbose_name='วัคซีนเข็ม ๒'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='vaccine_dose_3',
            field=models.BooleanField(default=False, verbose_name='วัคซีนเข็ม ๓'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='vaccine_dose_4',
            field=models.BooleanField(default=False, verbose_name='วัคซีนเข็ม ๔'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='vehicle_registration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ทะเบียนรถ'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='zone',
            field=models.CharField(blank=True, help_text='ระบุพื้นที่หรือโซนที่ปฏิบัติงาน', max_length=100, null=True, verbose_name='พื้นที่/โซน'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(max_length=255, verbose_name='ตำแหน่ง/หน้าที่'),
        ),
    ]
