# Generated by Django 5.2.7 on 2025-11-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_staffprofile_age_staffprofile_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='title',
            field=models.CharField(help_text='เช่น นาย, นาง, น.ส., พล.อ., พล.ต. ฯลฯ', max_length=50, verbose_name='ยศ'),
        ),
    ]
