# Generated by Django 5.2.7 on 2025-11-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_staffprofile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='cropped_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/cropped/', verbose_name='รูปภาพที่ Crop แล้ว'),
        ),
    ]
