# Generated by Django 5.2.7 on 2025-11-04 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_photo_cropped_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='เช่น A, B, C', max_length=10, unique=True, verbose_name='รหัสโซน')),
                ('name', models.CharField(help_text='เช่น กอร.ถปภ. ณ ม.นครพนม', max_length=255, verbose_name='ชื่อโซน')),
                ('description', models.TextField(blank=True, help_text='รายละเอียดเพิ่มเติมเกี่ยวกับโซน', null=True, verbose_name='คำอธิบาย')),
                ('work_start_date', models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มปฏิบัติงาน')),
                ('work_end_date', models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุดการปฏิบัติงาน')),
                ('order', models.IntegerField(default=0, help_text='ใช้สำหรับเรียงลำดับการแสดงผล', verbose_name='ลำดับการแสดงผล')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name': 'โซนปฏิบัติงาน',
                'verbose_name_plural': 'โซนปฏิบัติงาน',
                'db_table': 'zones',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='ระบุพื้นที่หรือโซนที่ปฏิบัติงาน', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_profiles', to='registry.zone', verbose_name='พื้นที่/โซน'),
        ),
    ]
