# Generated by Django 5.2.7 on 2025-11-05 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_zone_alter_staffprofile_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='work_end_date',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='work_start_date',
        ),
    ]
