# Generated by Django 5.2.7 on 2025-11-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_remove_zone_work_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='person_type',
            field=models.CharField(blank=True, help_text='เช่น บุคคลชั้นในสุด, บุคคลชั้นใน, บุคคลทั่วไป ฯลฯ', max_length=100, null=True, verbose_name='ประเภทบุคคล'),
        ),
    ]
