# Generated by Django 5.2.7 on 2025-11-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_staffprofile_person_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='ถ้าไม่กรอก จะใช้ชื่อเต็มอัตโนมัติ (ใช้สำหรับย่อชื่อยาว)', max_length=255, null=True, verbose_name='ชื่อที่แสดงบนบัตร'),
        ),
    ]
