# Generated by Django 5.2.7 on 2025-12-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_staffprofile_display_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['last_line', 'first_line'], 'verbose_name': 'ข้อมูลบุคลากร', 'verbose_name_plural': 'ข้อมูลบุคลากร'},
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='title',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='first_line',
            field=models.CharField(default='', help_text='ยศและชื่อรวมกัน (ไม่เว้นวรรค) เช่น นายสมชาย, นางสาวสมหญิง', max_length=200, verbose_name='ยศชื่อ'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='last_line',
            field=models.CharField(default='', help_text='นามสกุล เช่น ใจดี, รักษาดี', max_length=100, verbose_name='นามสกุล'),
        ),
    ]
