# Generated by Django 5.2.7 on 2025-12-10 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_alter_staffprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='test_atk',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='test_rt_pcr',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='test_temperature',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='vaccine_dose_1',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='vaccine_dose_2',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='vaccine_dose_3',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='vaccine_dose_4',
        ),
    ]
