# Generated by Django 5.2.7 on 2025-12-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_remove_staffprofile_test_atk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='is_reserve_badge',
            field=models.BooleanField(default=False, help_text='เมื่อเลือก จะไม่แสดงชื่อ-สกุลบนบัตร (เว้นว่าง)', verbose_name='บัตรสำรอง'),
        ),
    ]
