# Generated by Django 5.2.7 on 2025-11-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='ชื่อตัวตั้งค่า เช่น qr_secret_key, logo_file, primary_color', max_length=100, unique=True, verbose_name='Key')),
                ('value', models.TextField(verbose_name='ค่า')),
                ('setting_type', models.CharField(choices=[('string', 'ข้อความ'), ('integer', 'ตัวเลข'), ('boolean', 'True/False'), ('json', 'JSON'), ('file', 'ไฟล์'), ('color', 'สี')], default='string', max_length=20, verbose_name='ประเภท')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
            ],
            options={
                'verbose_name': 'การตั้งค่าระบบ',
                'verbose_name_plural': 'การตั้งค่าระบบ',
                'db_table': 'system_settings',
                'ordering': ['key'],
            },
        ),
    ]
