# Generated by Django 5.2.7 on 2025-11-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'ส่งข้อมูล'), ('review', 'ตรวจสอบ'), ('approve', 'อนุมัติ'), ('reject', 'ส่งกลับ'), ('edit', 'แก้ไข'), ('comment', 'แสดงความคิดเห็น')], max_length=20, verbose_name='การกระทำ')),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='สถานะเดิม')),
                ('new_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='สถานะใหม่')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='ความคิดเห็น/หมายเหตุ')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='ดำเนินการเมื่อ')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'บันทึกการอนุมัติ',
                'verbose_name_plural': 'บันทึกการอนุมัติ',
                'db_table': 'approval_logs',
                'ordering': ['-performed_at'],
            },
        ),
    ]
