# Generated by Django 5.2.7 on 2025-11-01 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvallog',
            name='badge_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='registry.badgerequest', verbose_name='คำขอออกบัตร'),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_logs', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ดำเนินการ'),
        ),
    ]
