# Generated by Django 5.2.7 on 2025-11-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallog',
            name='action',
            field=models.CharField(choices=[('submit', 'ส่งข้อมูล'), ('review', 'ตรวจสอบ'), ('approve', 'อนุมัติ'), ('reject', 'ส่งกลับ'), ('edit', 'แก้ไข'), ('comment', 'แสดงความคิดเห็น'), ('edit_badge', 'แก้ไขบัตร'), ('change_color', 'เปลี่ยนสีบัตร'), ('reprint', 'พิมพ์ซ้ำ'), ('badge_created', 'สร้างบัตร'), ('printed', 'พิมพ์บัตร'), ('badge_deleted', 'ลบบัตร')], max_length=20, verbose_name='การกระทำ'),
        ),
    ]
