# Generated by Django 5.2.7 on 2025-11-01 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='templates/badges/', verbose_name='ไฟล์แม่แบบ')),
                ('background_color', models.CharField(max_length=7, verbose_name='สีพื้นหลัง')),
                ('text_color', models.CharField(default='#000000', max_length=7, verbose_name='สีข้อความ')),
                ('logo_position_x', models.IntegerField(default=0, verbose_name='ตำแหน่งโลโก้ X')),
                ('logo_position_y', models.IntegerField(default=0, verbose_name='ตำแหน่งโลโก้ Y')),
                ('photo_position_x', models.IntegerField(default=0, verbose_name='ตำแหน่งรูปภาพ X')),
                ('photo_position_y', models.IntegerField(default=0, verbose_name='ตำแหน่งรูปภาพ Y')),
                ('qr_position_x', models.IntegerField(default=0, verbose_name='ตำแหน่ง QR X')),
                ('qr_position_y', models.IntegerField(default=0, verbose_name='ตำแหน่ง QR Y')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name': 'แม่แบบบัตร',
                'verbose_name_plural': 'แม่แบบบัตร',
                'db_table': 'badge_templates',
            },
        ),
        migrations.CreateModel(
            name='BadgeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อประเภท')),
                ('color', models.CharField(choices=[('pink', 'ชมพู - บุคลากรชั้นใน'), ('red', 'แดง - บุคลากรชั้นใน'), ('yellow', 'เหลือง - บุคลากรชั้นกลาง'), ('green', 'เขียว - บุคลากรชั้นนอก')], max_length=20, unique=True, verbose_name='สี')),
                ('color_code', models.CharField(help_text='เช่น #FFC0CB', max_length=7, verbose_name='รหัสสี (Hex)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name': 'ประเภทบัตร',
                'verbose_name_plural': 'ประเภทบัตร',
                'db_table': 'badge_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_at', models.DateTimeField(auto_now_add=True, verbose_name='พิมพ์เมื่อ')),
                ('printer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อเครื่องพิมพ์')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
            ],
            options={
                'verbose_name': 'บันทึกการพิมพ์',
                'verbose_name_plural': 'บันทึกการพิมพ์',
                'db_table': 'print_logs',
                'ordering': ['-printed_at'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=50, unique=True, verbose_name='หมายเลขบัตร')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code')),
                ('qr_data', models.TextField(verbose_name='ข้อมูล QR')),
                ('qr_signature', models.CharField(max_length=255, verbose_name='ลายเซ็น QR')),
                ('badge_file', models.FileField(blank=True, null=True, upload_to='badges/', verbose_name='ไฟล์บัตร')),
                ('is_printed', models.BooleanField(default=False, verbose_name='พิมพ์แล้ว')),
                ('printed_count', models.IntegerField(default=0, verbose_name='จำนวนครั้งที่พิมพ์')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานได้')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_created', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
            ],
            options={
                'verbose_name': 'บัตร',
                'verbose_name_plural': 'บัตร',
                'db_table': 'badges',
                'ordering': ['-created_at'],
            },
        ),
    ]
