# Generated by Django 5.2.7 on 2025-11-01 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0001_initial'),
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='staff_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='registry.staffprofile', verbose_name='ข้อมูลบุคลากร'),
        ),
        migrations.AddField(
            model_name='badgetemplate',
            name='badge_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='badges.badgetype', verbose_name='ประเภทบัตร'),
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='badges', to='badges.badgetype', verbose_name='ประเภทบัตร'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_logs', to='badges.badge', verbose_name='บัตร'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='printed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_logs', to=settings.AUTH_USER_MODEL, verbose_name='ผู้พิมพ์'),
        ),
    ]
