# Generated by Django 5.2.7 on 2025-11-05 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeSignatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, max_length=100, null=True, verbose_name='ยศ/คำนำหน้า')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('department', models.CharField(max_length=255, verbose_name='หน่วยงาน')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='ตำแหน่ง')),
                ('signature_image', models.ImageField(help_text='ไฟล์ PNG โปร่งใส ขนาดแนะนำ 400x150 px', upload_to='signatures/', verbose_name='ลายเซ็นต์อิเล็กทรอนิกส์')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name': 'ผู้เซ็นบัตร',
                'verbose_name_plural': 'ผู้เซ็นบัตร',
                'db_table': 'badge_signatories',
                'ordering': ['rank', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='badge',
            name='signature_type',
            field=models.CharField(choices=[('none', 'ไม่มีลายเซ็น'), ('manual', 'เซ็นต์มือจริง'), ('electronic', 'ลายเซ็นต์อิเล็กทรอนิกส์')], default='none', max_length=20, verbose_name='ประเภทลายเซ็น'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='signature_type',
            field=models.CharField(choices=[('manual', 'เซ็นต์มือจริง'), ('electronic', 'ลายเซ็นต์อิเล็กทรอนิกส์')], default='manual', max_length=20, verbose_name='ประเภทลายเซ็น'),
        ),
        migrations.AddField(
            model_name='badge',
            name='signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges', to='badges.badgesignatory', verbose_name='ผู้เซ็น'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_logs', to='badges.badgesignatory', verbose_name='ผู้เซ็น'),
        ),
    ]
