# Generated by Django 5.2.7 on 2025-11-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_badgesignatory_badge_signature_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='revision_count',
            field=models.IntegerField(default=0, help_text='นับจำนวนครั้งที่มีการแก้ไขบัตรหลังจากออกเลขแล้ว', verbose_name='จำนวนครั้งที่แก้ไข'),
        ),
        migrations.AddField(
            model_name='badge',
            name='revision_reason',
            field=models.TextField(blank=True, help_text='บันทึกเหตุผลการแก้ไขครั้งล่าสุด เช่น ชื่อยาว, เปลี่ยนโซน, เปลี่ยนสีบัตร', null=True, verbose_name='เหตุผลในการแก้ไขล่าสุด'),
        ),
    ]
