# Generated by Django 5.2.7 on 2025-11-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('dashboard_summary', 'สรุป Dashboard'), ('department_summary', 'สรุปตามหน่วยงาน'), ('badge_type_summary', 'สรุปตามประเภทบัตร'), ('status_summary', 'สรุปตามสถานะ'), ('daily_summary', 'สรุปรายวัน')], max_length=50, verbose_name='ประเภทรายงาน')),
                ('report_key', models.CharField(blank=True, help_text='เช่น department_id, badge_type_id, date', max_length=255, null=True, verbose_name='Key รายงาน')),
                ('data', models.JSONField(verbose_name='ข้อมูลรายงาน')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='สร้างเมื่อ')),
                ('expires_at', models.DateTimeField(blank=True, help_text='ถ้าไม่ระบุจะไม่หมดอายุ', null=True, verbose_name='หมดอายุเมื่อ')),
            ],
            options={
                'verbose_name': 'แคชรายงาน',
                'verbose_name_plural': 'แคชรายงาน',
                'db_table': 'report_caches',
                'ordering': ['-generated_at'],
                'unique_together': {('report_type', 'report_key')},
            },
        ),
    ]
